# Generated by Django 5.2.12 on 2026-03-17 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.IntegerField()),
                ('operator_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['client_id'], name='support_cha_client__e9c872_idx'), models.Index(fields=['operator_id'], name='support_cha_operato_6d087b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(max_length=10)),
                ('sender_id', models.IntegerField()),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support_chat.conversation')),
            ],
            options={
                'indexes': [models.Index(fields=['conversation'], name='support_cha_convers_26b670_idx'), models.Index(fields=['created_at'], name='support_cha_created_bc9b67_idx')],
            },
        ),
    ]
