# Generated by Django 5.2.12 on 2026-03-17 11:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='message',
            name='support_cha_convers_26b670_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='support_cha_created_bc9b67_idx',
        ),
        migrations.AddField(
            model_name='conversation',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='client_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='operator_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='support_chat.conversation'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_id',
            field=models.BigIntegerField(),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='support_cha_convers_71a38a_idx'),
        ),
    ]
