# Generated by Django 5.2.12 on 2026-03-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_chat', '0003_message_file_message_file_name_message_file_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='ai_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='bot_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
