# Generated by Django 5.2.12 on 2026-03-18 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support_chat', '0005_botconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='bot_enabled',
        ),
    ]
