# Generated by Django 5.2.12 on 2026-03-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_chat', '0006_remove_conversation_bot_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='bot_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
